/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.managment.system;

/**
 *
 * @author sajath
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form splashScreen
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        doctorIcon = new javax.swing.JLabel();
        patientIcon = new javax.swing.JLabel();
        receptionistIcon = new javax.swing.JLabel();
        adminIcon = new javax.swing.JLabel();
        doctorButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        receptionistButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        doctorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new/doctor (1).png"))); // NOI18N
        jPanel2.add(doctorIcon);
        doctorIcon.setBounds(530, 120, 120, 140);

        patientIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new/patient.png"))); // NOI18N
        jPanel2.add(patientIcon);
        patientIcon.setBounds(790, 120, 130, 130);

        receptionistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new/receptionist.png"))); // NOI18N
        jPanel2.add(receptionistIcon);
        receptionistIcon.setBounds(530, 350, 120, 120);

        adminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new/unauthorized-person.png"))); // NOI18N
        jPanel2.add(adminIcon);
        adminIcon.setBounds(790, 360, 130, 110);

        doctorButton.setBackground(new java.awt.Color(204, 204, 204));
        doctorButton.setText("Doctor");
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(doctorButton);
        doctorButton.setBounds(550, 270, 81, 25);

        patientButton.setBackground(new java.awt.Color(204, 204, 204));
        patientButton.setText("Patient");
        jPanel2.add(patientButton);
        patientButton.setBounds(830, 270, 86, 25);

        receptionistButton.setBackground(new java.awt.Color(204, 204, 204));
        receptionistButton.setText("Receptionist");
        jPanel2.add(receptionistButton);
        receptionistButton.setBounds(540, 480, 123, 25);

        adminButton.setBackground(new java.awt.Color(204, 204, 204));
        adminButton.setText("Admin");
        jPanel2.add(adminButton);
        adminButton.setBounds(810, 480, 94, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new/shutterstock_1021932094 (1).jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JButton doctorButton;
    private javax.swing.JLabel doctorIcon;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton patientButton;
    private javax.swing.JLabel patientIcon;
    private javax.swing.JButton receptionistButton;
    private javax.swing.JLabel receptionistIcon;
    // End of variables declaration//GEN-END:variables
}
